### ISSUE TITLE
Create custom automation flows

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#281]
### Summary

In addition the the built-in workflows we provide to allow you to automatically triage your items, add items from a repository, and archive when they are no longer needed on your project, we will allow users to create custom automations. This will give flexibility to set other project fields and build workflows custom to a use case.

![project workflows page](https://user-images.githubusercontent.com/101840513/263340714-87f7d224-8bdf-40fc-b018-835d7a62ee22.png
)

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why this issue was removed from the public roadmap. We are aware of gaps in the automation flows for projects. We will continue to ship updates to existing workflows, such as our recent release of [auto close when complete](https://github.blog/changelog/2024-04-25-github-issues-projects-auto-close-issue-project-workflow/) and are continuing to investigate how we can add even more flexibility with custom automation flows. However we currently do not have a timeline for when this would be available.
