### ISSUE TITLE
Commenting on unchanged lines in a pull request

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#347]
### Summary

Review comments are the primary way reviewers provide feedback to the author and other reviewers during the review phase of a pull request, but currently comments can only be added to the 3 lines before or after a changed line. We intend to allow users to add comments and suggest changes on any line in any file changed in the pull request.

![image](https://user-images.githubusercontent.com/2503052/144141747-af9a93b1-13c0-4a90-aa8a-97cca814ac08.png)

### Intended Outcome

This will improve the review experience and increase review quality by allowing users to comment on lines that were not changed (but maybe should have been). Users will no longer need to add a comment to a random changed line and reference a line number when providing feedback about missing a change.

### How will it work?

A users can add a comment, reply to a comment, or suggest changes to any line of a changed file, not just the 3 lines surrounding a change.

**Comment by ankneis** [comment]
Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014).

**Comment by ankneis** [comment]
We wanted to provide more details on why this issue was removed from the public roadmap. Code review improvements remain a key priority for us. We're removing this issue from the roadmap while we develop more certainty around our scope and timelines.

In the meantime, we’d love for you to upvote and share your thoughts in this [dedicated discussion](https://github.com/orgs/community/discussions/9099), else start a new discussion if needed!
