### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#355]
### Summary

![demo of navigating between organizations and using the theme switcher command with the command palette](https://user-images.githubusercontent.com/33528647/138329062-c54f0651-d4cd-4f29-83a0-a1786660a33a.gif)

The Command Palette is a new GitHub surface designed to improve how users navigate around GitHub and execute time saving commands. Jump to your organizations and repositories quickly, and search within them for pull requests, issues, projects, files, and more. Execute commands to optimize your workflows, all without lifting your hands from the keyboard. 

### Intended Outcome

The command palette gives new users and super fans alike a new way to cut down on the time necessary to navigate GitHub and execute commands for common workflows. 

### How will it work?

Open the command palette using one of the following keyboard shortcuts:
- Windows and Linux: <kbd>Ctl</kbd><kbd>k</kbd> or <kbd>Ctl</kbd><kbd>alt</kbd><kbd>k</kbd> 
- Mac: <kbd>⌘</kbd><kbd>k</kbd> or <kbd>⌘</kbd><kbd>option</kbd><kbd>k</kbd>

Use modes to find specific types of resources: 
   - <kbd>#</kbd> Search for issues, pull requests, discussions, and projects
   - <kbd>!</kbd> Search for projects
   - <kbd>@</kbd> Search for users, organizations, and repositories
   - <kbd>/</kbd> Search for files within a repository scope 

For more information, review [command palette documentation](https://docs.github.com/en/get-started/using-github/github-command-palette).

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why this issue was removed from the public roadmap. We're still evaluating ways to improve this feature so we are taking this GA (General Availability) issue off the roadmap until our timelines are more defined.  But, if you're interested in trying out Command Palette, it is currently available as a feature preview.  Find out how to toggle on the feature preview [here](https://docs.github.com/en/get-started/using-github/exploring-early-access-releases-with-feature-preview#exploring-public-preview-releases-with-feature-preview).  Keep watching the roadmap in the meantime and give us feedback on the preview if you try it out!
