### ISSUE TITLE
Actions Performance Metrics

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#561]
**Summary**
In this first iteration of Actions Performance Metrics, our goal is to provide you with performance data for workflows and jobs in every repository across your entire enterprise. 

The success rate, average run time, repository adoption and total number of jobs per workflow helps you get an holistic understanding of workflow performance. Workflow performance is dependent on individual jobs in the workflow, so, success rate, average run time and average start time for individual jobs is equally important for measuring performance. Actions Performance Metrics couples this data with historical trends presenting you with a high level view of CI/CD performance. 

Actions Performance Metrics provides data to answer these common questions:
- Which of my workflows and jobs take the longest to complete?
- Which of my workflow and jobs are the most successful?
- How long are the individual steps in a workflow taking per run?
- How many repositories in my company are using a specific workflow?
- How is the performance of my workflows and jobs trending over time? Are things getting faster or slower?

**Comment by ankneis** [comment]
This has been deprioritized

**Comment by ankneis** [comment]
Thank you for your participation in the Actions Usage Metrics beta program, and more importantly, for all of your valuable feedback. As we look back at what we’ve learned from Actions Usage Metrics, we discovered the biggest problem we can solve for our Actions customers right now is to improve our billing experience with more robust cost analysis tools.

We will deprecate the Actions Usage Metrics beta program in order to focus on improving our billing experience, which will include usage insights. Please take a moment to export your usage data by visiting the Insights section of your organization, navigating to Actions Usage Metrics, and clicking on the Export button in the top right of the table.

Again, we want to thank everyone for their interest in Actions Usage Metrics and continued support as we innovate to stay ahead of the curve
